### ISSUE TITLE
Trouble Installing

### ISSUE THREAD

**Issue by KWS53** [anntzer/redeal#29] opened 2023-04-12 18:17 UTC
Win10, Python 3.9.10/and Python 3.11 - both with PIP23
![Python_ReDeal_Error](https://user-images.githubusercontent.com/130591046/231550170-005a8a04-8eb6-4d57-abcb-e8aaa9ba4700.png)

**Comment by anntzer** [comment] 2023-04-18 15:37
I realize this is somewhat unhelpful, but I cannot reproduce the problem: the installation works fine for me on Windows 10 Pro and Python 3.11, though I install Python from https://docs.conda.io/en/latest/miniconda.html; perhaps give that a try?  (Carefully uninstall other installed Pythons first, though.)

**Comment by vasarm** [comment] 2023-04-22 13:13
I had a similar problem, but I replaced the .dll file with a file from Bo's website https://privat.bahnhof.se/wb758135/bridge/dll.html version 2.9.0. Then everything worked.

**Comment by anntzer** [comment] 2023-04-22 21:21
Ah thanks, that's a great suggestion.  I switched the package to auto-download these, @KWS53 can you give it a try again?

**Comment by anntzer** [comment] 2023-08-13 12:53
Closing for lack of reply, but feel free to ping if more help is needed.

**Closed by anntzer** 2023-08-13 12:53 UTC
