### ISSUE TITLE
[Question] How to run simulation inside Python?

### ISSUE THREAD

**Issue by Kungsgeten** [anntzer/redeal#6] opened 2017-12-04 08:53 UTC
Hi!

I'd like to try and use Redeal in a web application, and was wondering if you could give me some tips. What I'd like to to do is to run a Simulation (or multiple copies of one), and get the result as a Deal (or a list of them). In other words: I'd like to run simulations inside of Python, and get the results as data structures, but couldn't really figure out how to do so from looking at the source code.

**Comment by anntzer** [comment] 2017-12-04 09:07
Hi,
I just pushed a tiny change that allows you to do something like
```
from redeal import Simulation
from redeal.__main__ import Main

class MySim(Simulation):
    def __init__(self):
        self._north_spades = []

    def accept(self, deal):
        return deal.north.hcp >= 12

    def do(self, deal):
        self._north_spades.append(len(deal.north.spades))

sim = MySim()
main = Main()
main.parse_args(["-S", "AK - - -"])
main.generate(sim)

print(sim._north_spades)
```
(counting the number of spades of North when North has at least 12HCP and South has the spade AK; not a very interesting example at all, just the first thing that came to my mind).

Basically just create a Main object and call parse_args with what you'd normally pass as command-line arguments, and a simulation class.  Probably not the best API (I didn't really have this usage in mind back when I wrote this), but should be good enough to get you started?

**Comment by Kungsgeten** [comment] 2017-12-04 15:24
Thank you! I looked at `Main.generate` and have started writing a function of my own, which seems to work. I'll have to experiment with predeal and similar though. Here's my take (example):

```
import redeal

def generate_deal(accept_func=None, predeal=None):
    if predeal is None:
        predeal = {}
    dealer = redeal.Deal.prepare(predeal)
    if accept_func is None:
        return dealer()
    for i in range(1000):
        deal = dealer()
        if accept_func(deal):
            return deal

def test_accept(deal):
    return deal.north.hcp >= 18

deals = [generate_deal(accept_func=test_accept) for i in range(10)]

```

**Comment by anntzer** [comment] 2017-12-04 19:15
Setting up predeal is a bit more tricky so that's why I suggested just passing it as "command-line arguments" (i.e. via parse_args).

**Comment by Kungsgeten** [comment] 2017-12-04 23:23
Yes I see. I looked into the predeal part of Main, and the command-line arguments, and came up with a function to generate a predeal. Something like this:

```
import redeal

def generate_deal(accept_func=None, predeal=None):
    if predeal is None:
        predeal = {}
    dealer = redeal.Deal.prepare(predeal)
    if accept_func is None:
        return dealer()
    for i in range(1000):
        deal = dealer()
        if accept_func(deal):
            return deal

def predeal(*args):
    return {redeal.global_defs.Seat[args[i]]: redeal.H(args[i + 1])
            for i in range(0, len(args), 2)}

def test_accept(deal):
    return deal.north.hcp >= 18

deals = [generate_deal(test_accept, predeal('S', 'KJ8432 - - -')) for i in range(10)]
```

**Comment by anntzer** [comment] 2017-12-05 04:48
I'll close this for now, as I think the issue is settled.  But I'll happily take PRs that make such usage easier.
I'd be happy to hear about your webapp too.

**Closed by anntzer** 2017-12-05 04:48 UTC

**Comment by Kungsgeten** [comment] 2017-12-05 08:05
Yes thank you very much for your help. The webapp will be similar to another site of mine: www.correctcontract.com
