### ISSUE TITLE
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by EmanuelU** [anntzer/redeal#24] opened 2021-05-27 12:57 UTC
No matter what I try, with different version of python I can't run redeal on my new computer.

The same code worked great on another machine.

Something with the DLLs.

Running AMD Razen 5900

$ redeal
Traceback (most recent call last):
  File "c:\users\x\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\x\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\x\AppData\Roaming\Python\Python37\Scripts\redeal.exe\__main__.py", line 4, in <module>
  File "C:\Users\x\AppData\Roaming\Python\Python37\site-packages\redeal\__init__.py", line 7, in <module>
    from .redeal import *
  File "C:\Users\x\AppData\Roaming\Python\Python37\site-packages\redeal\redeal.py", line 20, in <module>
    from . import dds, util
  File "C:\Users\x\AppData\Roaming\Python\Python37\site-packages\redeal\dds.py", line 166, in <module>
    dll = DLL(dll_path)
  File "c:\users\x\appdata\local\programs\python\python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed

**Comment by EmanuelU** [comment] 2021-05-27 13:36
when I went to site-packages/redeal
and deleted the dds-64.dll it works.

**Comment by EmanuelU** [comment] 2021-05-27 13:46
ok, it seems redeal works but not the solves.

**Comment by EmanuelU** [comment] 2021-05-27 13:49
have I somehow failed to build the dlls properly?
I am on a windows machine.

**Comment by EmanuelU** [comment] 2021-05-27 14:55
Solved by manually downloading dlls from Bo Haglunds website.

**Comment by anntzer** [comment] 2021-05-31 11:42
I cannot reproduce the failure myself.  Closing, as a workaround seems available too.

**Closed** 2021-05-31 11:42 UTC
